server.port=8080
spring.application.name=inventra-dd-be

inventra.app.jwtSecret=UCXwJsCbQOjyLJzCWevfwNZCshcaaEgRcvqcKDGNo
inventra.app.jwtExpirationMs=86400000

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-2.pooler.supabase.com:6543/postgres?prepareThreshold=0
spring.datasource.username=postgres.wezwzuzaxsplgckjtxxu
spring.datasource.password=DianDidaktikaInventra

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB