server.port=8080
spring.application.name=inventra-dd-be

inventra.app.jwtSecret=UCXwJsCbQOjyLJzCWevfwNZCshcaaEgRcvqcKDGNo
inventra.app.jwtExpirationMs=86400000

spring.datasource.url=jdbc:h2:mem:inventradb
spring.datasource.username=inventra-dev
spring.datasource.password=ibuprofen-2026